name: Build and Publish VSIX

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Update package.json version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          npm version --no-git-tag-version $TAG_VERSION

      - name: Compile Extension
        run: npm run build

      - name: Package VSIX
        run: npx vsce package

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-vsix
          path: '*.vsix'

      - name: Publish to VSCode Marketplace
        run: npx vsce publish --packagePath $(ls *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Publish to Open VSX Registry
        continue-on-error: true
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Commit updated package.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Update package.json version to match tag"
          git push origin HEAD:master
